### ISSUE TITLE
No reboot menu.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/player-chromeapp#29]
Ubuntu 14.04 (32bit)
Chrome App Player (39.0.2171.99 (64-bit))

When a physical power button is pressed on a media player, there is no menu brought up for reboot/sleep/shutdown.

**Comment by alanclayton** [comment]
@btfrise How is this related to Chrome App Player? Wouldn't this be an OS thing?

**Comment by btfrise** [comment]
@alanclayton this has been confirmed as an OS issue. Closing.
