### ISSUE TITLE
CAP may or may not update webM video in Storage

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/player-chromeapp#38]
Steps to reproduce:
1. Upload a webm video to Storage, and add to an HTML5 Video Widget in a presentation
2. Assign this presentation to a display
3. Verify that video is running on display
4. Upload a different video (with the same name as the original video) to Storage, overwriting the original file
5. Verify that the Storage file has been updated by browsing to it in incognito mode.

Result:
Video may or may not update within a random period of time (tests were 25 minutes, 45 minutes and longer - a couple of hours before it updated).  Continuing the same test, overwriting the video a second time after it did update the first time, it never updated again within a 24 hour period.

How it should work:
CAP should poll storage every 15 minutes, downloading and displaying content that has changed in Storage.

OS:
Windows 7

Chrome Ver:
41.0.2272.101

**Comment by mfarooq2000** [comment]
@AlexKolenoff is this issue happening only with WebM videos?

**Comment by AlexKolenoff** [comment]
@mfarooq2000 This issue arose from a client ticket and webm videos were only involved so I haven't tested with anything else (I assume you mean images).  Do you need me to test with images in order to move forward?

**Comment by mfarooq2000** [comment]
@AlexKolenoff Just around last week we tested it successfully, so was curious if its specific.

I will investigate.

**Comment by mfarooq2000** [comment]
@AlexKolenoff I tested it again with webm video, Player is downloading file in 15 minutes if modified.

If client is still seeing the issue, then you may want to verify there are on latest version of CAP 1.24.27. And the videos are hosted on rise storage

**Comment by AlexKolenoff** [comment]
I replicated the issue they had on two of my displays and in my own company on a new presentation using the current HTML5 video widget.  The first time I tested it with the client it updated fairly quickly, but after that I couldn't get the same results.  Since it was inconsistent for both me and the client, could you please update it (rename it and upload it) a second time to see if it updates then?

**Comment by mfarooq2000** [comment]
@AlexKolenoff I diad upload a file, after the presentation started showing that, I uploaded another video with the same name. After 15 to 16 minutes from first video upload the second video started playing.

I can try again if you want me to.

**Comment by AlexKolenoff** [comment]
@mfarooq2000 I would like to find out the difference between what you are doing (if consistently successful) and what I am doing.  I forgot to answer your question about CAP version, it is 1.24.27 on both of my displays.
Can you please see if it updates again?  If so then I will try with the same presentation and same files as you on my own displays.

**Comment by mfarooq2000** [comment]
@AlexKolenoff Okay I will run the test again to make sure it is consistent and send you my presentation details.

**Comment by mfarooq2000** [comment]
@AlexKolenoff I was using Video item that's why could replicate issue earlier.

Now with HTML5 Video widget I am seeing the issue and its related to the Widget or storage.

@tejohnso I uploaded a video to storage and added to HTML5 Video widget, it played on player successfully

Then I uploaded another video with the same name to storage, 
Player after 15 minutes requests the video item and this time it got 404 error.

In screen capture you will see the same url worked the 1st time and it failed 2nd time.
http://screencast.com/t/YOmUpL8nu

http://screencast.com/t/YOmUpL8nu

**Comment by tejohnso** [comment]
Are you still getting a 404 on that?  It comes back 200 for me.

**Comment by mfarooq2000** [comment]
@tejohnso I am finding when we update same video on storage it gets new generation number.
And HTML5 video widget is using the generation number in URL.

It becomes issue when:

1. In HTML5 video widget in presentation choose a video file item, save and publish
2. Run the presentation on a player, Let the video file download and play
3. Upload the same video item in storage
4. After 15 minutes player will try to download the video again from storage server

At this time the generation number would be different on server and Widget doesn't look like know about the change, its still requesting file with old generation number and so getting 404 error.

**Comment by tejohnso** [comment]
We definitely shouldn't be using a specific generation number in the url as that will lead to problems like this.  I'm still not sure why you're getting a 404 and I'm not.  But in any case, the URLs should not contain specific version/generation numbers.  @stulees is this something you could look into?

**Comment by stulees** [comment]
@tejohnso The URL used for a video when a file has been chosen from storage is provided by our `rise-storage` web component. I'm not aware of generation numbers in the url. The url is constructed in a storage response handler in the component, either here - https://github.com/Rise-Vision/web-component-rise-storage/blob/master/rise-storage.html#L506 or here - https://github.com/Rise-Vision/web-component-rise-storage/blob/master/rise-storage.html#L516 . 

The `rise-storage` web component is set to have a refresh of 15 minutes in the Video Widget, in which it does another request and the widget reloads the video based on the url provided by the component again. @donnapep anything to add? Do you know about specific generation numbers in the url?

**Comment by stulees** [comment]
@mfarooq2000 Slightly off topic, but do you know if it is required to construct a URL for Rise Cache when it is a video like so - `http://localhost:9494/video.ext?url=...  `? Is the `video.ext` part necessary, or does Rise Cache ignore that?

**Comment by stulees** [comment]
@mfarooq2000 To clarify, `ext` would be the actual extension of the file, eg. `webm`

**Comment by mfarooq2000** [comment]
@stulees in Chrome App Player its only interested in the url query parameter. But I am not sure about native player and the API reference we have for third party developers.

**Comment by donnapep** [comment]
@tejohnso The generation numbers are part of the mediaLink property, which is what gets passed to the Widgets - http://goo.gl/PBB27v.

**Comment by stulees** [comment]
@mfarooq2000 Okay good to know, thanks

**Comment by alanclayton** [comment]
@tejohnso @donnapep @stulees can somebody clarify what needs to be done to resolve the issue with updated files resulting in a 404?

**Comment by tejohnso** [comment]
@donnapep That's the data Google returns for the object.  In our case we don't want to fixate on one version of the file, so we should probably use the selfLink + "?alt=media" rather than using the mediaLink.
@alanclayton fyi

**Comment by donnapep** [comment]
@AlexKolenoff  OK, sounds like this should be moved to the Rise Storage repo then as the URL needs to be updated. Thx.

**Comment by tejohnso** [comment]
@donnapep the widget should not use the media link that comes from googles returned object

**Comment by donnapep** [comment]
@tejohnso Right, I plan to update to use selfLink + "?alt=media" as per your earlier comment.

**Comment by donnapep** [comment]
@tejohnso Ah, I think perhaps you thought I was asking to log this in your Storage repo. To clarify, it should be logged in the `web-component-rise-storage` repo. Thx.

**Comment by AlexKolenoff** [comment]
@donnapep   This has now been logged in the web-component-rise-storage repo.
