### ISSUE TITLE
Expired cache files are not removed after (simulated) 31+ days.

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/player-chromeapp#40]
Steps to reproduce:
1. Have presentation running view (with file verified in cache)
2. Exit player.
3. Remove video from presentation.
4. Set date forward 31+ days (I've changed it from May 4 to Jun 17)
5. Start player.
6. Examine cached files from configuration page/web widget.

Result:
Cached file is still present on system.

How it should work:
Cached file should not be present on system.

Additional information:
This is in the testing/qa version of player.

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=153136b9-8dd3-41d1-84ec-918cc1748f16?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55
**presentation may change (slightly) as it is still being used in current QA

OS:
OSX, Ubuntu 14.04, Windows 7, presumably Chrome OS.

Chrome Ver:
42.0.2311 (stable)

**Comment by mfarooq2000** [comment]
@mfisher11 fixed, not deployed yet. Working on the other issue #41

**Comment by mfarooq2000** [comment]
@mfisher11 its deployed now

**Comment by mfisher11** [comment]
@mfarooq2000 This is resolved.  Closing issue.
