### ISSUE TITLE
When video in presentation is replaced with new video (same name), it is downloaded to cache, but never shown

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/player-chromeapp#41]
Steps to reproduce:
1. Have video (served from rise storage) running in presentation.
2. Upload replacement video with the same name (overwriting original).
3. Wait 15+ minutes.

Result:
Video will stop playing, leaving an empty placeholder.

How it should work:
New video should start playing.

**Additional information:
Cache viewed from html configuration page.  Both cached files (identified by size) are present on player, but neither one plays.
This is in the testing/qa version of player.

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=153136b9-8dd3-41d1-84ec-918cc1748f16?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

OS:
OSX, Ubuntu 14.04, Windows 7, Chrome OS

Chrome Ver:
42.0.2311 (stable)

**Comment by mfarooq2000** [comment]
@mfisher11 is this happening in QA or production version of CAP?

**Comment by mfisher11** [comment]
@mfarooq2000 In the QA version.  Sorry.  I'll update the description on both of the new issues.

**Comment by mfarooq2000** [comment]
@mfisher11 its fixed and deployed now.

**Comment by mfisher11** [comment]
@mfarooq2000 Resolved and closing.
