### ISSUE TITLE
ChromeBit Hangs looking For network

### ISSUE THREAD

**Issue by BaddMann** [Rise-Vision/player-chromeapp#64]
Chromebit being tested here to see if we can use it instead of a full size chromebox.
[The Chromebit is an ASUS](https://www.asus.com/us/Chrome-Devices/Chromebit-CS10/specifications/) 
It's having no issues being an enrolled ChromeOS Device, but the RisePlayer is having issues connecting to a network that it's already connected too.

I'm willing to do more troubleshooting, but I haven't figured out where the logs are yet.

Thank you in advance for any advise.

**Comment by fjvallarino** [comment]
Hi there,

We don’t support ChromeOS at this time, and the Rise Chrome App Player for ChromeOS is now an open-source community project. If you would like more information on this, please see the “ChromeOS” section of https://help.risevision.com/user/create-a-display

If you are looking for other media players, you can check out our Store link at https://store.risevision.com/products/?cat=Media%20Players 

Thanks!

**Comment by BaddMann** [comment]
Funnily enough thats how I came to file the issue.
I was on the open source project where the community should be able to support the question.
 
We adopted chromeOS for its simplicity, manageability and lack of baggage.
Any particular reason you're no longer supporting the chromeOS?

**Comment by robb-price** [comment]
Hello there!

Here is the community conversation that outlines the reasons for why we stopped supporting the Chrome App Player: https://community.risevision.com/rise_vision_inc/topics/chrome-application-player-on-hold-due-to-issues.

I would strongly suggest posting this issue as a new question in the community, to see if other users who are using the Chrome App Player can assist.

Thanks!
