### ISSUE TITLE
caching videos

### ISSUE THREAD

**Issue by krzyzaq** [Rise-Vision/player-chromeapp#65]
Hi, where is the cache folder created for the video files?
Can the buffer be set as needed (bigger) and to download cache in background?
By the way - the videos are a little buggy on the raspberry pi 3 with newest jessie distro.
I'll would try on rpi2 but I'm afraid that it will be much worse than on rpi3, that still is a bit expensive.
The web plays but is chunky. The same resolution mp4 file stops the player completley.
Is there a work around or I'll have to save all in web?

**Comment by alanclayton** [comment]
Hi @krzyzaq Rise Vision doesn't support Raspberry Pi. You'll have better luck posting your questions in the Community here, https://community.risevision.com/rise_vision_inc/topics/community-supported-raspberry-pi-2-instructions-riseberry

Thanks!
