### ISSUE TITLE
Chrome OS player doesn't save Display ID

### ISSUE THREAD

**Issue by blandman** [Rise-Vision/player-chromeapp#66]
When I setup the Ride Player (tried both versions on the Chrome store), I set the Display ID, it works great. If the Chrome device is rebooted, the Display ID is lost and prompts for a display ID every time.

Is there a way to set the displayID using a Google Admin config file?

**Comment by btfrise** [comment]
Hey there @blandman!

If this device is a Google Managed Device, it's likely that you need to make a small change in your management console.

On admin.google.com, go to Device Management > Chrome > Device Settings

Under Sign-in Settings, change "Erase all local user info, settings, and state after each sign-out" to "Do not erase all local user info, settings, and state after sign-out."

![userdata](https://cloud.githubusercontent.com/assets/8458926/20487970/0132c9e0-afcb-11e6-83a1-b2c55565ea73.png)

**Comment by blandman** [comment]
Wow I didn't even see this setting! Thank you! I will test it out tomorrow.

**Comment by blandman** [comment]
This did the trick! Thank you!
This was the last little issue preventing us from using this awesome product for our signs. Google's Sign Builder doesn't hold a candle to this.
